export type CatalogCourse={
  slug:string;title:string;description:string;level:string;category:"Lộ trình CEFR"|"Kỹ năng"|"Mục tiêu"|"Chuyên sâu";
  duration:string;units:number;skills:string[];target:string;featured?:boolean;
};
export const courseCatalog:CatalogCourse[]=[
  {slug:"english-a0-foundation",title:"A0 — Bắt đầu từ con số 0",description:"Bảng chữ cái, âm cơ bản, số, lời chào và những câu sinh tồn đầu tiên.",level:"A0",category:"Lộ trình CEFR",duration:"4 tuần",units:8,skills:["Phonics","Từ nền tảng","Hội thoại"],target:"/topics/daily-life",featured:true},
  {slug:"english-a1-communication",title:"A1 — Giao tiếp nền tảng",description:"Giới thiệu bản thân, gia đình, nhà cửa, lịch trình, mua sắm và hỏi đường.",level:"A1",category:"Lộ trình CEFR",duration:"8 tuần",units:12,skills:["Listening","Speaking","Grammar"],target:"/topics/daily-life",featured:true},
  {slug:"english-a2-everyday",title:"A2 — Tiếng Anh đời sống",description:"Xử lý tình huống du lịch, dịch vụ, sức khỏe và công việc quen thuộc.",level:"A2",category:"Lộ trình CEFR",duration:"10 tuần",units:14,skills:["Conversation","Reading","Writing"],target:"/topics/travel",featured:true},
  {slug:"english-b1-independent",title:"B1 — Giao tiếp độc lập",description:"Kể trải nghiệm, giải thích quan điểm và giao tiếp tự tin trong học tập, công việc.",level:"B1",category:"Lộ trình CEFR",duration:"12 tuần",units:16,skills:["Fluency","Vocabulary","Writing"],target:"/topics/work",featured:true},
  {slug:"english-b2-confident",title:"B2 — Giao tiếp tự tin",description:"Thảo luận chủ đề phức tạp, đàm phán và sử dụng sắc thái ngôn ngữ tự nhiên.",level:"B2",category:"Lộ trình CEFR",duration:"14 tuần",units:18,skills:["Debate","Nuance","Presentation"],target:"/topics/culture"},
  {slug:"english-c1-advanced",title:"C1 — Tiếng Anh nâng cao",description:"Ngôn ngữ linh hoạt cho môi trường học thuật, chuyên nghiệp và liên văn hóa.",level:"C1",category:"Lộ trình CEFR",duration:"16 tuần",units:20,skills:["Academic","Professional","Precision"],target:"/grammar"},
  {slug:"english-c2-mastery",title:"C2 — Làm chủ tiếng Anh",description:"Hiểu và diễn đạt chính xác các ý tưởng tinh tế, trừu tượng và chuyên sâu.",level:"C2",category:"Lộ trình CEFR",duration:"Tự chọn",units:18,skills:["Style","Inference","Mastery"],target:"/grammar"},
  {slug:"listening-lab",title:"Listening Lab",description:"Từ âm nối và từ yếu đến podcast, bài giảng, thông báo và nhiều giọng nói.",level:"A1–C1",category:"Kỹ năng",duration:"60 giờ",units:12,skills:["Dictation","Shadowing","Comprehension"],target:"/library"},
  {slug:"speaking-confidence",title:"Speaking Confidence",description:"Phản xạ hội thoại, kể chuyện, trình bày quan điểm và xử lý ngập ngừng.",level:"A1–C1",category:"Kỹ năng",duration:"50 giờ",units:12,skills:["Fluency","Role-play","Feedback"],target:"/practice"},
  {slug:"reading-power",title:"Reading Power",description:"Đọc nhanh, đoán nghĩa, tìm ý chính và phân tích văn bản theo cấp độ.",level:"A1–C1",category:"Kỹ năng",duration:"40 giờ",units:10,skills:["Skimming","Inference","Vocabulary"],target:"/library"},
  {slug:"writing-clear",title:"Writing Clearly",description:"Từ câu, đoạn văn đến email, bài luận và báo cáo có cấu trúc rõ ràng.",level:"A1–C1",category:"Kỹ năng",duration:"45 giờ",units:12,skills:["Cohesion","Accuracy","Register"],target:"/grammar"},
  {slug:"pronunciation-ipa",title:"Phát âm & IPA toàn diện",description:"44 âm IPA, trọng âm, nối âm, ngữ điệu và luyện cặp âm dễ nhầm.",level:"A0–B2",category:"Chuyên sâu",duration:"30 giờ",units:10,skills:["IPA","Stress","Connected speech"],target:"/pronunciation"},
  {slug:"grammar-in-context",title:"Ngữ pháp trong ngữ cảnh",description:"Hệ thống ngữ pháp A1–C1 với công thức, lỗi thường gặp và ví dụ thực tế.",level:"A1–C1",category:"Chuyên sâu",duration:"55 giờ",units:15,skills:["Forms","Meaning","Usage"],target:"/grammar"},
  {slug:"vocabulary-builder",title:"Vocabulary Builder",description:"Từ vựng theo chủ đề, collocation, word family và ôn tập thông minh FSRS.",level:"A1–C1",category:"Chuyên sâu",duration:"Mỗi ngày",units:16,skills:["Collocation","Word family","FSRS"],target:"/dictionary"},
  {slug:"business-english",title:"Business English",description:"Email, họp, thuyết trình, đàm phán và giao tiếp đa văn hóa.",level:"B1–C1",category:"Mục tiêu",duration:"10 tuần",units:12,skills:["Meetings","Email","Negotiation"],target:"/topics/work"},
  {slug:"travel-english",title:"English for Travel",description:"Sân bay, khách sạn, nhà hàng, hỏi đường và xử lý tình huống khẩn cấp.",level:"A1–B1",category:"Mục tiêu",duration:"6 tuần",units:10,skills:["Survival English","Listening","Role-play"],target:"/topics/travel"},
  {slug:"ielts-roadmap",title:"IELTS Roadmap",description:"Chiến thuật và luyện tập Listening, Reading, Writing, Speaking theo band mục tiêu.",level:"B1–C1",category:"Mục tiêu",duration:"12 tuần",units:16,skills:["IELTS","Mock test","Strategy"],target:"/topics/exam"},
  {slug:"toeic-workplace",title:"TOEIC Workplace",description:"Từ vựng công sở, nghe tình huống và đọc nhanh cho môi trường doanh nghiệp.",level:"A2–B2",category:"Mục tiêu",duration:"10 tuần",units:14,skills:["TOEIC","Workplace","Timing"],target:"/topics/exam"},
  {slug:"interview-ready",title:"International Interview Ready",description:"Hồ sơ cá nhân, câu trả lời STAR, phỏng vấn hành vi và câu hỏi ngược.",level:"B1–C1",category:"Mục tiêu",duration:"4 tuần",units:8,skills:["STAR","Confidence","Career"],target:"/topics/work"},
  {slug:"english-for-tech",title:"English for Technology",description:"Sản phẩm số, code review, báo lỗi, tài liệu, bảo mật và thảo luận AI.",level:"B1–C1",category:"Mục tiêu",duration:"8 tuần",units:12,skills:["Tech","Documentation","AI"],target:"/topics/technology"},
];
