import { AlertTriangle, BookOpenCheck, CheckCircle2, Sparkles, Volume2 } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { GrammarControls, GrammarDialogButton, GrammarDialogClose } from "@/components/learning/GrammarControls";
import { SpeakButton } from "@/components/learning/SpeakButton";

type GrammarTopic={level:string;title:string;summary:string;formula:string[];uses:string[];examples:Array<{en:string;vi:string;context:string}>;mistakes:Array<{wrong:string;right:string;note:string}>;tip:string};
const grammar:GrammarTopic[]=[
  {level:"A1",title:"Present Simple",summary:"Diễn tả thói quen, lịch trình, sở thích và sự thật.",formula:["Khẳng định: S + V(s/es) + …","Phủ định: S + do/does not + V nguyên mẫu","Câu hỏi: Do/Does + S + V nguyên mẫu?"],uses:["Thói quen lặp lại: usually, often, every day","Sự thật hoặc trạng thái ổn định","Lịch trình cố định trong tương lai"],examples:[{en:"I practise English before breakfast.",vi:"Tôi luyện tiếng Anh trước bữa sáng.",context:"Thói quen"},{en:"Maya works in a design studio.",vi:"Maya làm việc tại một studio thiết kế.",context:"Công việc"},{en:"The train leaves at 7:30 tomorrow.",vi:"Tàu khởi hành lúc 7:30 sáng mai.",context:"Lịch trình"}],mistakes:[{wrong:"She work from home.",right:"She works from home.",note:"He/she/it cần -s hoặc -es."},{wrong:"Does he speaks English?",right:"Does he speak English?",note:"Sau does dùng động từ nguyên mẫu."}],tip:"Khi kể lịch sinh hoạt, hãy dùng Present Simple và thêm trạng từ tần suất trước động từ thường."},
  {level:"A1",title:"Present Continuous",summary:"Diễn tả điều đang xảy ra, tình huống tạm thời hoặc kế hoạch đã sắp xếp.",formula:["Khẳng định: S + am/is/are + V-ing","Phủ định: S + am/is/are not + V-ing","Câu hỏi: Am/Is/Are + S + V-ing?"],uses:["Hành động ngay lúc nói","Tình huống tạm thời quanh hiện tại","Kế hoạch cá nhân đã xác định"],examples:[{en:"I am waiting for the bus.",vi:"Tôi đang đợi xe buýt.",context:"Ngay lúc nói"},{en:"She is staying with her aunt this week.",vi:"Tuần này cô ấy đang ở cùng dì.",context:"Tạm thời"},{en:"We are meeting the client on Friday.",vi:"Chúng tôi sẽ gặp khách hàng vào thứ Sáu.",context:"Kế hoạch"}],mistakes:[{wrong:"I am know the answer.",right:"I know the answer.",note:"Know là động từ trạng thái, thường không dùng tiếp diễn."}],tip:"Hãy tìm dấu hiệu now, right now, at the moment, this week."},
  {level:"A1",title:"Articles: a, an, the",summary:"Giúp người nghe biết danh từ là chung chung, lần đầu nhắc đến hay đã xác định.",formula:["a + âm phụ âm: a university","an + âm nguyên âm: an hour","the + danh từ đã xác định hoặc duy nhất"],uses:["a/an khi nói một đối tượng chưa xác định","the khi cả hai bên đều biết đối tượng","Không dùng mạo từ khi nói chung về danh từ số nhiều/không đếm được"],examples:[{en:"I saw a movie. The movie was inspiring.",vi:"Tôi xem một bộ phim. Bộ phim đó rất truyền cảm hứng.",context:"Nhắc lần đầu → nhắc lại"},{en:"Could you close the door?",vi:"Bạn đóng cánh cửa đó giúp tôi nhé?",context:"Đã xác định"},{en:"Books can change lives.",vi:"Sách có thể thay đổi cuộc đời.",context:"Nói chung"}],mistakes:[{wrong:"She is an university student.",right:"She is a university student.",note:"University bắt đầu bằng âm /j/, là âm phụ âm."}],tip:"Chọn a/an theo âm đọc, không chỉ theo chữ cái đầu."},
  {level:"A2",title:"Past Simple",summary:"Kể hành động đã kết thúc tại một thời điểm trong quá khứ.",formula:["Khẳng định: S + V2/ed","Phủ định: S + did not + V nguyên mẫu","Câu hỏi: Did + S + V nguyên mẫu?"],uses:["Sự kiện đã kết thúc","Chuỗi hành động trong câu chuyện","Thói quen trong quá khứ"],examples:[{en:"We visited Hội An last summer.",vi:"Mùa hè trước chúng tôi đã thăm Hội An.",context:"Du lịch"},{en:"I opened the email, read it and called my manager.",vi:"Tôi mở email, đọc nó rồi gọi quản lý.",context:"Chuỗi sự kiện"},{en:"Did you enjoy the workshop?",vi:"Bạn có thích buổi workshop không?",context:"Hỏi trải nghiệm"}],mistakes:[{wrong:"I didn't went there.",right:"I didn't go there.",note:"Sau did/didn't dùng động từ nguyên mẫu."}],tip:"Gắn câu chuyện với mốc thời gian như yesterday, last week, in 2025."},
  {level:"A2",title:"Comparatives",summary:"So sánh hai người, vật hoặc tình huống.",formula:["Tính từ ngắn: adj-er + than","Tính từ dài: more + adj + than","Bằng nhau: as + adj + as"],uses:["So sánh đặc điểm","Đưa ra lựa chọn","Mô tả thay đổi với better, worse, further"],examples:[{en:"This route is faster than the highway.",vi:"Tuyến đường này nhanh hơn đường cao tốc.",context:"Di chuyển"},{en:"Online meetings are more convenient for our team.",vi:"Họp trực tuyến thuận tiện hơn cho nhóm.",context:"Công việc"},{en:"The second task is not as difficult as the first.",vi:"Nhiệm vụ thứ hai không khó bằng nhiệm vụ đầu.",context:"Học tập"}],mistakes:[{wrong:"more easier",right:"easier",note:"Không dùng more cùng tính từ đã có -er."}],tip:"Với good/bad, dùng dạng bất quy tắc better/worse."},
  {level:"A2",title:"Modal verbs",summary:"Diễn tả khả năng, lời khuyên, sự cho phép và nghĩa vụ.",formula:["S + can/could/should/must + V nguyên mẫu","Phủ định: modal + not + V","Câu hỏi: Modal + S + V?"],uses:["can/could: khả năng hoặc đề nghị","should: lời khuyên","must/have to: nghĩa vụ"],examples:[{en:"Could you speak more slowly?",vi:"Bạn có thể nói chậm hơn không?",context:"Đề nghị lịch sự"},{en:"You should back up your files.",vi:"Bạn nên sao lưu tệp.",context:"Lời khuyên"},{en:"Visitors must show their ID.",vi:"Khách phải xuất trình giấy tờ.",context:"Quy định"}],mistakes:[{wrong:"She can speaks French.",right:"She can speak French.",note:"Sau modal dùng động từ nguyên mẫu."}],tip:"Could lịch sự hơn can khi nhờ vả trong dịch vụ hoặc công việc."},
  {level:"B1",title:"Present Perfect",summary:"Kết nối một trải nghiệm hoặc hành động quá khứ với hiện tại.",formula:["S + have/has + V3","S + have/has not + V3","Have/Has + S + V3?"],uses:["Trải nghiệm không nêu thời điểm cụ thể","Hành động kéo dài với for/since","Kết quả vừa xảy ra còn liên quan hiện tại"],examples:[{en:"I have visited Singapore twice.",vi:"Tôi đã đến Singapore hai lần.",context:"Trải nghiệm"},{en:"She has worked here since March.",vi:"Cô ấy làm ở đây từ tháng Ba.",context:"Kéo dài"},{en:"We have just finished the report.",vi:"Chúng tôi vừa hoàn thành báo cáo.",context:"Kết quả"}],mistakes:[{wrong:"I have seen him yesterday.",right:"I saw him yesterday.",note:"Có mốc quá khứ đã kết thúc thì dùng Past Simple."}],tip:"Since + điểm bắt đầu; for + khoảng thời gian."},
  {level:"B1",title:"Conditionals",summary:"Nói về kết quả thực tế, có khả năng hoặc giả định.",formula:["Zero: If + present, present","First: If + present, will + V","Second: If + past, would + V"],uses:["Zero: quy luật, sự thật","First: khả năng thật trong tương lai","Second: giả định ít thực tế"],examples:[{en:"If you heat ice, it melts.",vi:"Nếu làm nóng băng, nó tan.",context:"Quy luật"},{en:"If I finish early, I'll call you.",vi:"Nếu xong sớm, tôi sẽ gọi bạn.",context:"Kế hoạch có thể xảy ra"},{en:"If I had more time, I would learn Spanish.",vi:"Nếu có nhiều thời gian hơn, tôi sẽ học tiếng Tây Ban Nha.",context:"Giả định"}],mistakes:[{wrong:"If it will rain, we will stay home.",right:"If it rains, we will stay home.",note:"Mệnh đề if của First Conditional dùng hiện tại đơn."}],tip:"Dấu phẩy cần thiết khi mệnh đề if đứng trước; thường bỏ khi nó đứng sau."},
  {level:"B1",title:"Passive Voice",summary:"Nhấn mạnh hành động hoặc đối tượng nhận hành động hơn người thực hiện.",formula:["S + be (đúng thì) + V3","Tác nhân tùy chọn: by + người/vật"],uses:["Không biết hoặc không cần nói tác nhân","Văn phong quy trình, tin tức, học thuật","Nhấn mạnh kết quả"],examples:[{en:"English is spoken in many countries.",vi:"Tiếng Anh được nói ở nhiều quốc gia.",context:"Sự thật"},{en:"Your order has been shipped.",vi:"Đơn hàng của bạn đã được gửi.",context:"Dịch vụ"},{en:"The data will be reviewed tomorrow.",vi:"Dữ liệu sẽ được xem xét ngày mai.",context:"Công việc"}],mistakes:[{wrong:"The report was send.",right:"The report was sent.",note:"Bị động cần quá khứ phân từ V3."}],tip:"Giữ nguyên thì ở động từ be, sau đó thêm V3."},
  {level:"B2",title:"Reported Speech",summary:"Thuật lại lời nói và điều chỉnh thì, đại từ, thời gian theo góc nhìn mới.",formula:["said (that) + clause","told + object + (that) + clause","asked + if/whether hoặc question word"],uses:["Tóm tắt cuộc trò chuyện","Báo cáo yêu cầu hoặc câu hỏi","Kể lại thông tin"],examples:[{en:"She said that she was busy.",vi:"Cô ấy nói rằng cô ấy bận.",context:"Tường thuật"},{en:"He told me to wait outside.",vi:"Anh ấy bảo tôi đợi bên ngoài.",context:"Yêu cầu"},{en:"They asked whether I needed help.",vi:"Họ hỏi liệu tôi có cần giúp không.",context:"Câu hỏi yes/no"}],mistakes:[{wrong:"She told that she was tired.",right:"She said that she was tired.",note:"Tell thường cần tân ngữ: told me/us/him."}],tip:"Nếu thông tin vẫn luôn đúng, đôi khi không cần lùi thì."},
  {level:"B2",title:"Relative Clauses",summary:"Bổ sung thông tin cho người, vật, nơi chốn hoặc thời gian.",formula:["who + người","which/that + vật","where + nơi chốn; whose + sở hữu"],uses:["Mệnh đề xác định: thông tin cần thiết","Mệnh đề không xác định: thông tin thêm, có dấu phẩy"],examples:[{en:"The app that I use has offline lessons.",vi:"Ứng dụng tôi dùng có bài học ngoại tuyến.",context:"Xác định vật"},{en:"My mentor, who lives in London, calls every Friday.",vi:"Người hướng dẫn của tôi, sống ở London, gọi mỗi thứ Sáu.",context:"Thông tin thêm"},{en:"This is the café where we first met.",vi:"Đây là quán cà phê nơi chúng tôi gặp nhau lần đầu.",context:"Nơi chốn"}],mistakes:[{wrong:"The person which helped me",right:"The person who helped me",note:"Dùng who cho người."}],tip:"Không dùng that trong mệnh đề không xác định nằm giữa hai dấu phẩy."},
  {level:"C1",title:"Inversion",summary:"Đảo trợ động từ lên trước chủ ngữ để nhấn mạnh trong văn phong trang trọng.",formula:["Negative adverbial + auxiliary + S + V","Only after/when + clause + auxiliary + S + V"],uses:["Sau never, rarely, hardly, not only","Nhấn mạnh điều kiện hoặc trình tự","Văn viết và diễn thuyết trang trọng"],examples:[{en:"Never have I seen such rapid progress.",vi:"Tôi chưa từng thấy sự tiến bộ nhanh đến vậy.",context:"Nhấn mạnh"},{en:"Only after the meeting did I understand the issue.",vi:"Chỉ sau cuộc họp tôi mới hiểu vấn đề.",context:"Trình tự"},{en:"Not only did she apologize, but she also fixed the mistake.",vi:"Cô ấy không chỉ xin lỗi mà còn sửa lỗi.",context:"Lập luận"}],mistakes:[{wrong:"Never I have seen this.",right:"Never have I seen this.",note:"Đưa trợ động từ lên trước chủ ngữ."}],tip:"Dùng có chọn lọc; trong hội thoại thường ngày, trật tự câu bình thường tự nhiên hơn."},
];

export default function GrammarPage(){
  return <PageShell eyebrow="GRAMMAR LIBRARY" title="Ngữ pháp dễ hiểu">
    <section className="knowledge-intro"><div><span><Sparkles size={17}/> HỌC THEO NGỮ CẢNH</span><h2>Không chỉ nhớ công thức.<br/>Hãy hiểu cách dùng.</h2></div><p>Mỗi chủ điểm có công thức, cách dùng, bản dịch, lỗi thường gặp và ví dụ trong đời sống, học tập, công việc.</p></section>
    <GrammarControls/>
    <div className="grammar-grid">{grammar.map((item,index)=>{const id=`grammar-${index}`;return <article data-grammar-card data-level={item.level} data-search={`${item.title} ${item.summary} ${item.uses.join(" ")}`.toLowerCase()} key={item.title}><span>{item.level}</span><BookOpenCheck size={25}/><h3>{item.title}</h3><p>{item.summary}</p><blockquote>{item.examples[0].en}</blockquote><GrammarDialogButton id={id}/><section id={id} popover="auto" className="grammar-detail grammar-lesson"><GrammarDialogClose id={id}/><small>{item.level} • GRAMMAR DEEP DIVE</small><h2>{item.title}</h2><p>{item.summary}</p><h3>Công thức</h3><div className="grammar-formula">{item.formula.map(line=><span key={line}>{line}</span>)}</div><h3>Khi nào sử dụng?</h3><ul>{item.uses.map(use=><li key={use}><CheckCircle2/>{use}</li>)}</ul><h3>Ví dụ theo ngữ cảnh</h3><div className="context-examples">{item.examples.map(example=><article key={example.en}><small>{example.context}</small><SpeakButton text={example.en} label={`Nghe ${example.en}`}><Volume2 size={17}/></SpeakButton><b>{example.en}</b><span>{example.vi}</span></article>)}</div><h3>Lỗi thường gặp</h3><div className="common-mistakes">{item.mistakes.map(mistake=><article key={mistake.wrong}><AlertTriangle/><div><del>{mistake.wrong}</del><b>{mistake.right}</b><p>{mistake.note}</p></div></article>)}</div><div className="grammar-tip"><Sparkles/><p><b>Mẹo ghi nhớ</b>{item.tip}</p></div></section></article>})}</div>
  </PageShell>
}
