export type TopicData={
  slug:string;title:string;description:string;color:string;icon:string;hero:string;outcome:string;
  units:Array<{title:string;level:string;focus:string;description:string}>;
  words:Array<{word:string;ipa:string;meaning:string;example:string}>;
  phrases:Array<{en:string;vi:string;context:string}>;
  dialogue:Array<{speaker:string;en:string;vi:string}>;
  grammar:Array<{name:string;use:string;example:string}>;
};
export const topicCategories:TopicData[]=[
  {slug:"daily-life",title:"Cuộc sống hằng ngày",description:"Gia đình, nhà cửa, ăn uống, mua sắm và cảm xúc.",color:"#d8ef74",icon:"map",hero:"Biến những việc bạn làm mỗi ngày thành phản xạ tiếng Anh.",outcome:"Tự tin kể về bản thân, gia đình, thói quen và xử lý hội thoại đời sống.",units:[["Chào hỏi & giới thiệu","A0","Speaking","Tên, quê quán, nghề nghiệp và small talk."],["Gia đình & bạn bè","A1","Vocabulary","Quan hệ, tính cách và hoạt động cùng người thân."],["Nhà cửa & khu phố","A1","Listening","Phòng, đồ dùng, vị trí và hỏi đường."],["Thói quen hằng ngày","A1","Grammar","Lịch trình từ sáng đến tối và tần suất."],["Ăn uống & mua sắm","A2","Conversation","Gọi món, khẩu vị, giá cả và thanh toán."],["Cảm xúc & sức khỏe","A2","Speaking","Cảm xúc, triệu chứng và lời khuyên."]].map(([title,level,focus,description])=>({title,level,focus,description})),words:[["routine","/ruːˈtiːn/","thói quen","My morning routine starts at 6:30."],["neighbourhood","/ˈneɪ.bə.hʊd/","khu phố","There is a quiet park in my neighbourhood."],["relative","/ˈrel.ə.tɪv/","họ hàng","Most of my relatives live nearby."],["groceries","/ˈɡrəʊ.sər.iz/","thực phẩm","I buy groceries every Saturday."],["tidy","/ˈtaɪ.di/","gọn gàng","Could you keep your room tidy?"],["exhausted","/ɪɡˈzɔː.stɪd/","kiệt sức","I felt exhausted after work."]].map(([word,ipa,meaning,example])=>({word,ipa,meaning,example})),phrases:[["How has your day been?","Hôm nay của bạn thế nào?","Hỏi thăm"],["Could you give me a hand?","Bạn giúp tôi một tay được không?","Nhờ giúp"],["I'm just about to leave.","Tôi chuẩn bị đi đây.","Việc sắp làm"],["That works for me.","Như vậy phù hợp với tôi.","Chốt kế hoạch"]].map(([en,vi,context])=>({en,vi,context})),dialogue:[["Maya","Do you usually cook after work?","Bạn thường nấu ăn sau giờ làm à?"],["You","Most days, yes. I prepare simple meals.","Hầu hết các ngày là có. Tôi chuẩn bị món đơn giản."],["Maya","What do you make when you're in a hurry?","Khi vội bạn nấu món gì?"],["You","I normally make noodles with vegetables.","Tôi thường nấu mì với rau."]].map(([speaker,en,vi])=>({speaker,en,vi})),grammar:[["Present Simple","Nói thói quen","I walk to work three times a week."],["Adverbs of frequency","Nói tần suất","We usually have dinner together."],["There is / are","Mô tả nơi chốn","There are two cafés near my house."]].map(([name,use,example])=>({name,use,example}))},
  {slug:"travel",title:"Du lịch",description:"Sân bay, khách sạn, hỏi đường và nhà hàng.",color:"#ffc088",icon:"plane",hero:"Đi xa mà không ngại thiếu từ để nói.",outcome:"Tự xử lý hành trình từ đặt vé, nhập cảnh, khách sạn đến sự cố.",units:[["Lập kế hoạch","A1","Reading","Ngày đi, ngân sách, hành lý và lịch trình."],["Tại sân bay","A2","Listening","Check-in, an ninh và cửa khởi hành."],["Nhập cảnh","A2","Speaking","Mục đích, lưu trú và khai báo."],["Khách sạn","A2","Role-play","Nhận phòng, dịch vụ và khiếu nại."],["Hỏi đường","A1","Speaking","Tìm nơi và dùng giao thông công cộng."],["Nhà hàng","A2","Conversation","Đặt bàn, dị ứng và thanh toán."]].map(([title,level,focus,description])=>({title,level,focus,description})),words:[["boarding pass","/ˈbɔː.dɪŋ pɑːs/","thẻ lên máy bay","Please have your boarding pass ready."],["departure","/dɪˈpɑː.tʃər/","khởi hành","Our departure is delayed."],["accommodation","/əˌkɒm.əˈdeɪ.ʃən/","chỗ ở","The price includes accommodation."],["reservation","/ˌrez.əˈveɪ.ʃən/","đặt chỗ","I have a reservation under Nguyen."],["itinerary","/aɪˈtɪn.ər.ər.i/","lịch trình","Our itinerary includes three cities."],["currency","/ˈkʌr.ən.si/","tiền tệ","Where can I exchange currency?"]].map(([word,ipa,meaning,example])=>({word,ipa,meaning,example})),phrases:[["Where is the check-in counter?","Quầy làm thủ tục ở đâu?","Sân bay"],["Is early check-in available?","Có thể nhận phòng sớm không?","Khách sạn"],["Could you show me on the map?","Bạn chỉ trên bản đồ được không?","Hỏi đường"],["Does this contain peanuts?","Món này có đậu phộng không?","Nhà hàng"]].map(([en,vi,context])=>({en,vi,context})),dialogue:[["Receptionist","Do you have a reservation?","Bạn đã đặt phòng chưa?"],["You","Yes, it's under Nguyen.","Rồi, tên Nguyễn."],["Receptionist","May I see your passport?","Tôi xem hộ chiếu được không?"],["You","Of course. Is breakfast included?","Tất nhiên. Đã gồm bữa sáng chưa?"]].map(([speaker,en,vi])=>({speaker,en,vi})),grammar:[["Could / Would","Yêu cầu lịch sự","Could I have a room with a view?"],["Future arrangements","Kế hoạch đã định","We're flying on Friday."],["Indirect questions","Hỏi lịch sự","Could you tell me where gate 12 is?"]].map(([name,use,example])=>({name,use,example}))},
  {slug:"work",title:"Công việc",description:"Phỏng vấn, họp, email và thuyết trình.",color:"#9ddfd2",icon:"work",hero:"Giao tiếp chuyên nghiệp nhưng vẫn tự nhiên.",outcome:"Tham gia họp, viết email, trình bày và phỏng vấn rõ ràng.",units:[["Phỏng vấn","A2","Speaking","Kinh nghiệm, kỹ năng và câu trả lời STAR."],["Email","B1","Writing","Mở đầu, yêu cầu, theo dõi và kết thư."],["Họp nhóm","B1","Listening","Ý kiến, phản biện và đầu việc."],["Thuyết trình","B1","Speaking","Mở bài, chuyển ý, dữ liệu và Q&A."],["Đàm phán","B2","Role-play","Điều kiện, nhượng bộ và thỏa thuận."],["Feedback","B2","Conversation","Phản hồi rõ, cụ thể và tôn trọng."]].map(([title,level,focus,description])=>({title,level,focus,description})),words:[["deadline","/ˈded.laɪn/","hạn chót","Can we move the deadline?"],["agenda","/əˈdʒen.də/","chương trình họp","The budget is first on the agenda."],["stakeholder","/ˈsteɪkˌhəʊl.dər/","bên liên quan","We need stakeholder approval."],["proposal","/prəˈpəʊ.zəl/","đề xuất","I'll send the revised proposal."],["prioritise","/praɪˈɒr.ə.taɪz/","ưu tiên","Let's prioritise customer issues."],["feedback","/ˈfiːd.bæk/","phản hồi","Could you give me feedback?"]].map(([word,ipa,meaning,example])=>({word,ipa,meaning,example})),phrases:[["Could you walk us through the numbers?","Bạn trình bày các con số nhé?","Họp"],["I'd like to build on that point.","Tôi muốn phát triển thêm ý đó.","Thảo luận"],["Let's circle back tomorrow.","Ngày mai ta quay lại vấn đề này.","Hoãn"],["Please find the report attached.","Vui lòng xem báo cáo đính kèm.","Email"]].map(([en,vi,context])=>({en,vi,context})),dialogue:[["Manager","Could you give us a progress update?","Bạn cập nhật tiến độ được không?"],["You","We've completed the research.","Chúng tôi đã hoàn tất nghiên cứu."],["Manager","Are there any risks?","Có rủi ro nào không?"],["You","The timeline is tight, but we're on track.","Thời gian gấp, nhưng vẫn đúng tiến độ."]].map(([speaker,en,vi])=>({speaker,en,vi})),grammar:[["Present Perfect","Cập nhật tiến độ","We have completed the first phase."],["Hedging","Ý kiến mềm mại","It might be worth considering another option."],["Passive Voice","Nhấn mạnh quy trình","The report will be shared tomorrow."]].map(([name,use,example])=>({name,use,example}))},
];
const derived=[
  ["study","Học tập","Trường học, đại học, nghiên cứu và du học.","#c7b7f5","study","Học bằng tiếng Anh, không chỉ học tiếng Anh.","Theo dõi bài giảng, thảo luận, ghi chú và trình bày học thuật.",["lecture","assignment","evidence","analyse","scholarship","curriculum"]],
  ["culture","Xã hội & văn hóa","Môi trường, truyền thông và cộng đồng.","#f5c5bd","culture","Hiểu thế giới và diễn đạt quan điểm có chiều sâu.","Thảo luận văn hóa, xã hội và môi trường bằng ngôn ngữ cân bằng.",["community","heritage","sustainable","awareness","diversity","bias"]],
  ["technology","Công nghệ","Internet, lập trình, AI và bảo mật.","#b8d4f2","technology","Nói về công nghệ bằng ngôn ngữ rõ ràng.","Mô tả sản phẩm, lỗi, bảo mật và xu hướng AI.",["feature","device","update","bug","privacy","deploy"]],
  ["professional","Chuyên ngành","IT, marketing, tài chính, y tế và logistics.","#f3dea2","professional","Xây vốn tiếng Anh phục vụ đúng công việc.","Nắm ngôn ngữ liên ngành và tình huống thực tế theo nghề.",["requirement","campaign","revenue","symptom","inventory","shipment"]],
  ["exam","Luyện thi","CEFR, IELTS, TOEIC và phỏng vấn quốc tế.","#d1e8cf","exam","Hiểu tiêu chí, luyện đúng kỹ năng và đo tiến bộ.","Có chiến thuật, quản lý thời gian và ngôn ngữ phù hợp kỳ thi.",["criterion","fluency","coherence","paraphrase","distractor","relevant"]],
] as const;
for(const [slug,title,description,color,icon,hero,outcome,keywords] of derived){
  topicCategories.push({slug,title,description,color,icon,hero,outcome,
    units:keywords.map((keyword,index)=>({title:`${index+1}. ${keyword[0].toUpperCase()+keyword.slice(1)} trong ngữ cảnh`,level:index<2?"A2":"B1",focus:["Vocabulary","Listening","Speaking","Reading","Writing","Role-play"][index],description:`Học cách hiểu và sử dụng ${keyword} trong tình huống ${title.toLowerCase()}.`})),
    words:keywords.map((keyword)=>({word:keyword,ipa:"Nghe phát âm trong từ điển",meaning:`Từ khóa thiết yếu về ${description.toLowerCase()}`,example:`Use “${keyword}” naturally in a complete sentence about ${slug}.`})),
    phrases:[{en:`Could you explain your view on ${keywords[0]}?`,vi:`Bạn có thể giải thích quan điểm về ${keywords[0]} không?`,context:"Mở thảo luận"},{en:"Could you give me a practical example?",vi:"Bạn cho tôi một ví dụ thực tế được không?",context:"Hỏi sâu"},{en:"I agree to some extent, but…",vi:"Tôi đồng ý ở một mức độ, nhưng…",context:"Phản biện"},{en:"The main point is that…",vi:"Điểm chính là…",context:"Tóm tắt"}],
    dialogue:[{speaker:"Maya",en:`What interests you most about ${title.toLowerCase()}?`,vi:`Điều gì về ${title.toLowerCase()} khiến bạn quan tâm nhất?`},{speaker:"You",en:`I'm interested in ${keywords[0]} because it affects everyday life.`,vi:`Tôi quan tâm đến ${keywords[0]} vì nó ảnh hưởng đời sống.`},{speaker:"Maya",en:"Could you give me a specific example?",vi:"Bạn cho một ví dụ cụ thể được không?"},{speaker:"You",en:"Yes. Let me explain it through a recent situation.",vi:"Có. Để tôi giải thích qua một tình huống gần đây."}],
    grammar:[{name:"Present Perfect",use:"Kết nối trải nghiệm với hiện tại",example:`I have learned a lot about ${keywords[0]}.`},{name:"Conditionals",use:"Nêu giả định và kết quả",example:"If we understand the context, we will communicate more clearly."},{name:"Relative clauses",use:"Giải thích khái niệm",example:`This is a topic that affects many people.`}]});
}
export const topicBySlug:Record<string,TopicData>=Object.fromEntries(topicCategories.map(topic=>[topic.slug,topic]));
